## 关卡数据 - AutoLoad
## 100个主题关卡 (10区域 × 10Boss)
## 每种Boss独立形状、配色、棋盘大小、探索区参数

extends Node

const BOSS_GRID_SIZE = {
	"BAMBOO_TANUKI": Vector2i(3, 3),
	"BAMBOO_KITSUNE": Vector2i(4, 3),
	"BAMBOO_TENGU": Vector2i(3, 4),
	"BAMBOO_ONI": Vector2i(4, 4),
	"BAMBOO_JOROUGUMO": Vector2i(3, 3),
	"BAMBOO_HEBI": Vector2i(5, 3),
	"BAMBOO_TSURU": Vector2i(5, 3),
	"BAMBOO_KUMA": Vector2i(4, 4),
	"BAMBOO_ENMA": Vector2i(3, 4),
	"BAMBOO_RYUU": Vector2i(6, 3),
	"GEAR_AUTOMATON": Vector2i(3, 4),
	"GEAR_TANK": Vector2i(5, 3),
	"GEAR_ARACHNE": Vector2i(4, 3),
	"GEAR_DRILL": Vector2i(3, 4),
	"GEAR_CANNON": Vector2i(4, 3),
	"GEAR_HAWK": Vector2i(5, 3),
	"GEAR_BRONZE": Vector2i(4, 5),
	"GEAR_WORM": Vector2i(6, 3),
	"GEAR_KNIGHT": Vector2i(4, 5),
	"GEAR_COLOSSUS": Vector2i(5, 5),
	"OCEAN_JELLY": Vector2i(4, 4),
	"OCEAN_SHARK": Vector2i(6, 3),
	"OCEAN_KRAKEN": Vector2i(5, 5),
	"OCEAN_SIREN": Vector2i(3, 4),
	"OCEAN_CRAB": Vector2i(5, 3),
	"OCEAN_SEASERPENT": Vector2i(5, 3),
	"OCEAN_ANGLER": Vector2i(4, 3),
	"OCEAN_WHALE": Vector2i(6, 3),
	"OCEAN_CORAL": Vector2i(4, 4),
	"OCEAN_LEVIATHAN": Vector2i(6, 4),
	"LAVA_SALAMANDER": Vector2i(4, 3),
	"LAVA_PHOENIX": Vector2i(5, 4),
	"LAVA_MAGMA": Vector2i(4, 5),
	"LAVA_FIREWORM": Vector2i(6, 3),
	"LAVA_FIEND": Vector2i(4, 5),
	"LAVA_DRAKE": Vector2i(5, 4),
	"LAVA_ELEMENTAL": Vector2i(3, 4),
	"LAVA_CERBERUS": Vector2i(5, 4),
	"LAVA_PYROHYDRA": Vector2i(6, 4),
	"LAVA_IFRIT": Vector2i(5, 5),
	"MOON_RABBIT": Vector2i(3, 3),
	"MOON_FAIRY": Vector2i(3, 4),
	"MOON_CRANE": Vector2i(5, 3),
	"MOON_SILVERFOX": Vector2i(4, 3),
	"MOON_MOTH": Vector2i(5, 4),
	"MOON_OWL": Vector2i(4, 4),
	"MOON_QILIN": Vector2i(5, 4),
	"MOON_MOONSPIRIT": Vector2i(3, 4),
	"MOON_GUARDIAN": Vector2i(4, 5),
	"MOON_EMPRESS": Vector2i(5, 5),
	"ICE_WOLF": Vector2i(4, 3),
	"ICE_BEAR": Vector2i(4, 4),
	"ICE_ICEGOLEM": Vector2i(4, 5),
	"ICE_WRAITH": Vector2i(3, 4),
	"ICE_YETI": Vector2i(4, 4),
	"ICE_ICESPIDER": Vector2i(4, 3),
	"ICE_ICEPYTHON": Vector2i(6, 3),
	"ICE_FROSTBIRD": Vector2i(5, 4),
	"ICE_MAMMOTH": Vector2i(5, 4),
	"ICE_ICEQUEEN": Vector2i(4, 5),
	"TOXIC_MUSHROOM": Vector2i(3, 4),
	"TOXIC_TOAD": Vector2i(4, 3),
	"TOXIC_VINE": Vector2i(3, 5),
	"TOXIC_SLUG": Vector2i(5, 3),
	"TOXIC_SCORPION": Vector2i(5, 3),
	"TOXIC_BEETLE": Vector2i(4, 3),
	"TOXIC_ORCHID": Vector2i(3, 4),
	"TOXIC_SWAMPTHING": Vector2i(4, 4),
	"TOXIC_TOXHYDRA": Vector2i(6, 4),
	"TOXIC_PLAGUELORD": Vector2i(4, 5),
	"GHOST_SAMURAI": Vector2i(3, 4),
	"GHOST_GEISHA": Vector2i(3, 4),
	"GHOST_LANTERN": Vector2i(3, 3),
	"GHOST_SKELETON": Vector2i(3, 4),
	"GHOST_BANSHEE": Vector2i(3, 4),
	"GHOST_REAPER": Vector2i(4, 5),
	"GHOST_PUPPET": Vector2i(4, 4),
	"GHOST_SHADOWGHOST": Vector2i(4, 4),
	"GHOST_WRAITHKING": Vector2i(5, 5),
	"GHOST_LICH": Vector2i(4, 5),
	"CHAOS_MIMIC": Vector2i(3, 3),
	"CHAOS_EYE": Vector2i(4, 4),
	"CHAOS_BLOB": Vector2i(4, 3),
	"CHAOS_CHIMERA": Vector2i(5, 4),
	"CHAOS_RIFTWORM": Vector2i(6, 3),
	"CHAOS_CHAOSGARGOYLE": Vector2i(4, 4),
	"CHAOS_CHAOSGOLEM": Vector2i(5, 5),
	"CHAOS_CHAOSWITCH": Vector2i(4, 5),
	"CHAOS_CHAOSDRAGON": Vector2i(6, 4),
	"CHAOS_CHAOSLORD": Vector2i(5, 5),
	"VOID_PHANTOM": Vector2i(3, 4),
	"VOID_CRYSTAL": Vector2i(4, 4),
	"VOID_VOIDSERPENT": Vector2i(6, 3),
	"VOID_VOIDTITAN": Vector2i(5, 5),
	"VOID_VOIDREAPER": Vector2i(4, 5),
	"VOID_VOIDHYDRA": Vector2i(6, 4),
	"VOID_VOIDPHOENIX": Vector2i(5, 4),
	"VOID_VOIDDEMON": Vector2i(5, 5),
	"VOID_VOIDDRAGON": Vector2i(6, 5),
	"VOID_VOIDGOD": Vector2i(6, 6),
}

const LEVELS = [
	{
		"id": 1, "name": "竹林秘境·入口",
		"boss_name": "竹林狸猫", "boss_shape": "BAMBOO_TANUKI",
		"subtitle": "竹影婆娑间隐约传来低吟…",
		"color": Color(0.40,0.70,0.45),
		"tile_weights": { "WEAK": 0.40, "ARMOR": 0.03, "ABSORB": 0.01, "NORMAL": 0.56 },
		"bomb_count": 5, "base_clicks": 7,
		"turn_duration": 49.8, "boss_attack": 3, "boss_move_interval": 69.5,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 2, "name": "竹林秘境·竹径",
		"boss_name": "竹叶狐仙", "boss_shape": "BAMBOO_KITSUNE",
		"subtitle": "竹影婆娑间隐约传来低吟…",
		"color": Color(0.40,0.70,0.45),
		"tile_weights": { "WEAK": 0.39, "ARMOR": 0.03, "ABSORB": 0.01, "NORMAL": 0.56 },
		"bomb_count": 5, "base_clicks": 7,
		"turn_duration": 49.5, "boss_attack": 3, "boss_move_interval": 69.1,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 3, "name": "竹林秘境·石桥",
		"boss_name": "天狗", "boss_shape": "BAMBOO_TENGU",
		"subtitle": "竹影婆娑间隐约传来低吟…",
		"color": Color(0.40,0.70,0.45),
		"tile_weights": { "WEAK": 0.39, "ARMOR": 0.04, "ABSORB": 0.01, "NORMAL": 0.56 },
		"bomb_count": 5, "base_clicks": 7,
		"turn_duration": 49.2, "boss_attack": 3, "boss_move_interval": 68.7,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 4, "name": "竹林秘境·溪谷",
		"boss_name": "竹鬼", "boss_shape": "BAMBOO_ONI",
		"subtitle": "竹影婆娑间隐约传来低吟…",
		"color": Color(0.40,0.70,0.45),
		"tile_weights": { "WEAK": 0.39, "ARMOR": 0.04, "ABSORB": 0.02, "NORMAL": 0.56 },
		"bomb_count": 5, "base_clicks": 7,
		"turn_duration": 49.0, "boss_attack": 3, "boss_move_interval": 68.2,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 5, "name": "竹林秘境·古祠",
		"boss_name": "络新妇", "boss_shape": "BAMBOO_JOROUGUMO",
		"subtitle": "竹影婆娑间隐约传来低吟…",
		"color": Color(0.40,0.70,0.45),
		"tile_weights": { "WEAK": 0.39, "ARMOR": 0.04, "ABSORB": 0.02, "NORMAL": 0.56 },
		"bomb_count": 5, "base_clicks": 7,
		"turn_duration": 48.8, "boss_attack": 3, "boss_move_interval": 67.8,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 6, "name": "竹林秘境·密林",
		"boss_name": "蛇姬", "boss_shape": "BAMBOO_HEBI",
		"subtitle": "竹影婆娑间隐约传来低吟…",
		"color": Color(0.40,0.70,0.45),
		"tile_weights": { "WEAK": 0.38, "ARMOR": 0.04, "ABSORB": 0.02, "NORMAL": 0.56 },
		"bomb_count": 5, "base_clicks": 7,
		"turn_duration": 48.5, "boss_attack": 3, "boss_move_interval": 67.3,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 7, "name": "竹林秘境·瀑布",
		"boss_name": "仙鹤", "boss_shape": "BAMBOO_TSURU",
		"subtitle": "竹影婆娑间隐约传来低吟…",
		"color": Color(0.40,0.70,0.45),
		"tile_weights": { "WEAK": 0.38, "ARMOR": 0.05, "ABSORB": 0.02, "NORMAL": 0.56 },
		"bomb_count": 5, "base_clicks": 7,
		"turn_duration": 48.2, "boss_attack": 3, "boss_move_interval": 66.8,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 8, "name": "竹林秘境·山腰",
		"boss_name": "墨熊", "boss_shape": "BAMBOO_KUMA",
		"subtitle": "竹影婆娑间隐约传来低吟…",
		"color": Color(0.40,0.70,0.45),
		"tile_weights": { "WEAK": 0.38, "ARMOR": 0.05, "ABSORB": 0.02, "NORMAL": 0.56 },
		"bomb_count": 5, "base_clicks": 7,
		"turn_duration": 48.0, "boss_attack": 3, "boss_move_interval": 66.4,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 9, "name": "竹林秘境·云端",
		"boss_name": "灵猿", "boss_shape": "BAMBOO_ENMA",
		"subtitle": "竹影婆娑间隐约传来低吟…",
		"color": Color(0.40,0.70,0.45),
		"tile_weights": { "WEAK": 0.37, "ARMOR": 0.05, "ABSORB": 0.02, "NORMAL": 0.55 },
		"bomb_count": 5, "base_clicks": 7,
		"turn_duration": 47.8, "boss_attack": 4, "boss_move_interval": 66.0,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 10, "name": "竹林秘境·竹顶",
		"boss_name": "竹龙", "boss_shape": "BAMBOO_RYUU",
		"subtitle": "竹影婆娑间隐约传来低吟…",
		"color": Color(0.40,0.70,0.45),
		"tile_weights": { "WEAK": 0.37, "ARMOR": 0.05, "ABSORB": 0.02, "NORMAL": 0.55 },
		"bomb_count": 5, "base_clicks": 7,
		"turn_duration": 47.5, "boss_attack": 4, "boss_move_interval": 65.5,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 11, "name": "齿轮要塞·大门",
		"boss_name": "蒸汽傀儡", "boss_shape": "GEAR_AUTOMATON",
		"subtitle": "齿轮咬合的轰鸣声震耳欲聋…",
		"color": Color(0.70,0.55,0.30),
		"tile_weights": { "WEAK": 0.37, "ARMOR": 0.05, "ABSORB": 0.03, "NORMAL": 0.55 },
		"bomb_count": 5, "base_clicks": 7,
		"turn_duration": 47.2, "boss_attack": 4, "boss_move_interval": 65.0,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 12, "name": "齿轮要塞·齿轮厅",
		"boss_name": "铁甲战车", "boss_shape": "GEAR_TANK",
		"subtitle": "齿轮咬合的轰鸣声震耳欲聋…",
		"color": Color(0.70,0.55,0.30),
		"tile_weights": { "WEAK": 0.36, "ARMOR": 0.06, "ABSORB": 0.03, "NORMAL": 0.55 },
		"bomb_count": 5, "base_clicks": 7,
		"turn_duration": 47.0, "boss_attack": 4, "boss_move_interval": 64.6,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 13, "name": "齿轮要塞·蒸汽廊",
		"boss_name": "机械蜘蛛", "boss_shape": "GEAR_ARACHNE",
		"subtitle": "齿轮咬合的轰鸣声震耳欲聋…",
		"color": Color(0.70,0.55,0.30),
		"tile_weights": { "WEAK": 0.36, "ARMOR": 0.06, "ABSORB": 0.03, "NORMAL": 0.55 },
		"bomb_count": 5, "base_clicks": 7,
		"turn_duration": 46.8, "boss_attack": 4, "boss_move_interval": 64.2,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 14, "name": "齿轮要塞·熔炉",
		"boss_name": "钻地机", "boss_shape": "GEAR_DRILL",
		"subtitle": "齿轮咬合的轰鸣声震耳欲聋…",
		"color": Color(0.70,0.55,0.30),
		"tile_weights": { "WEAK": 0.36, "ARMOR": 0.06, "ABSORB": 0.03, "NORMAL": 0.55 },
		"bomb_count": 5, "base_clicks": 7,
		"turn_duration": 46.5, "boss_attack": 4, "boss_move_interval": 63.7,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 15, "name": "齿轮要塞·管道",
		"boss_name": "火炮台", "boss_shape": "GEAR_CANNON",
		"subtitle": "齿轮咬合的轰鸣声震耳欲聋…",
		"color": Color(0.70,0.55,0.30),
		"tile_weights": { "WEAK": 0.36, "ARMOR": 0.06, "ABSORB": 0.03, "NORMAL": 0.55 },
		"bomb_count": 5, "base_clicks": 7,
		"turn_duration": 46.2, "boss_attack": 4, "boss_move_interval": 63.2,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 16, "name": "齿轮要塞·钟楼",
		"boss_name": "机械鹰", "boss_shape": "GEAR_HAWK",
		"subtitle": "齿轮咬合的轰鸣声震耳欲聋…",
		"color": Color(0.70,0.55,0.30),
		"tile_weights": { "WEAK": 0.35, "ARMOR": 0.07, "ABSORB": 0.03, "NORMAL": 0.55 },
		"bomb_count": 5, "base_clicks": 7,
		"turn_duration": 46.0, "boss_attack": 4, "boss_move_interval": 62.8,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 17, "name": "齿轮要塞·铸造间",
		"boss_name": "铜人", "boss_shape": "GEAR_BRONZE",
		"subtitle": "齿轮咬合的轰鸣声震耳欲聋…",
		"color": Color(0.70,0.55,0.30),
		"tile_weights": { "WEAK": 0.35, "ARMOR": 0.07, "ABSORB": 0.03, "NORMAL": 0.55 },
		"bomb_count": 6, "base_clicks": 7,
		"turn_duration": 45.8, "boss_attack": 5, "boss_move_interval": 62.4,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 18, "name": "齿轮要塞·指挥室",
		"boss_name": "齿轮蠕虫", "boss_shape": "GEAR_WORM",
		"subtitle": "齿轮咬合的轰鸣声震耳欲聋…",
		"color": Color(0.70,0.55,0.30),
		"tile_weights": { "WEAK": 0.35, "ARMOR": 0.07, "ABSORB": 0.04, "NORMAL": 0.55 },
		"bomb_count": 6, "base_clicks": 7,
		"turn_duration": 45.5, "boss_attack": 5, "boss_move_interval": 61.9,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 19, "name": "齿轮要塞·通风井",
		"boss_name": "蒸汽骑士", "boss_shape": "GEAR_KNIGHT",
		"subtitle": "齿轮咬合的轰鸣声震耳欲聋…",
		"color": Color(0.70,0.55,0.30),
		"tile_weights": { "WEAK": 0.34, "ARMOR": 0.07, "ABSORB": 0.04, "NORMAL": 0.55 },
		"bomb_count": 6, "base_clicks": 7,
		"turn_duration": 45.2, "boss_attack": 5, "boss_move_interval": 61.5,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 20, "name": "齿轮要塞·核心",
		"boss_name": "齿轮巨人", "boss_shape": "GEAR_COLOSSUS",
		"subtitle": "齿轮咬合的轰鸣声震耳欲聋…",
		"color": Color(0.70,0.55,0.30),
		"tile_weights": { "WEAK": 0.34, "ARMOR": 0.07, "ABSORB": 0.04, "NORMAL": 0.55 },
		"bomb_count": 6, "base_clicks": 8,
		"turn_duration": 45.0, "boss_attack": 5, "boss_move_interval": 61.0,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 21, "name": "深渊之海·浅滩",
		"boss_name": "水母女王", "boss_shape": "OCEAN_JELLY",
		"subtitle": "深海中回荡着未知生物的呼唤…",
		"color": Color(0.25,0.50,0.80),
		"tile_weights": { "WEAK": 0.34, "ARMOR": 0.08, "ABSORB": 0.04, "NORMAL": 0.55 },
		"bomb_count": 6, "base_clicks": 8,
		"turn_duration": 44.8, "boss_attack": 5, "boss_move_interval": 60.5,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 22, "name": "深渊之海·珊瑚礁",
		"boss_name": "铁齿鲨", "boss_shape": "OCEAN_SHARK",
		"subtitle": "深海中回荡着未知生物的呼唤…",
		"color": Color(0.25,0.50,0.80),
		"tile_weights": { "WEAK": 0.33, "ARMOR": 0.08, "ABSORB": 0.04, "NORMAL": 0.55 },
		"bomb_count": 6, "base_clicks": 8,
		"turn_duration": 44.5, "boss_attack": 5, "boss_move_interval": 60.1,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 23, "name": "深渊之海·暗流",
		"boss_name": "深海章鱼", "boss_shape": "OCEAN_KRAKEN",
		"subtitle": "深海中回荡着未知生物的呼唤…",
		"color": Color(0.25,0.50,0.80),
		"tile_weights": { "WEAK": 0.33, "ARMOR": 0.08, "ABSORB": 0.04, "NORMAL": 0.55 },
		"bomb_count": 6, "base_clicks": 8,
		"turn_duration": 44.2, "boss_attack": 5, "boss_move_interval": 59.6,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 24, "name": "深渊之海·沉船",
		"boss_name": "海妖", "boss_shape": "OCEAN_SIREN",
		"subtitle": "深海中回荡着未知生物的呼唤…",
		"color": Color(0.25,0.50,0.80),
		"tile_weights": { "WEAK": 0.33, "ARMOR": 0.08, "ABSORB": 0.04, "NORMAL": 0.55 },
		"bomb_count": 6, "base_clicks": 8,
		"turn_duration": 44.0, "boss_attack": 5, "boss_move_interval": 59.2,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 25, "name": "深渊之海·深沟",
		"boss_name": "钢壳蟹", "boss_shape": "OCEAN_CRAB",
		"subtitle": "深海中回荡着未知生物的呼唤…",
		"color": Color(0.25,0.50,0.80),
		"tile_weights": { "WEAK": 0.33, "ARMOR": 0.08, "ABSORB": 0.05, "NORMAL": 0.55 },
		"bomb_count": 6, "base_clicks": 8,
		"turn_duration": 43.8, "boss_attack": 6, "boss_move_interval": 58.8,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 26, "name": "深渊之海·洞穴",
		"boss_name": "海蛇", "boss_shape": "OCEAN_SEASERPENT",
		"subtitle": "深海中回荡着未知生物的呼唤…",
		"color": Color(0.25,0.50,0.80),
		"tile_weights": { "WEAK": 0.32, "ARMOR": 0.09, "ABSORB": 0.05, "NORMAL": 0.54 },
		"bomb_count": 6, "base_clicks": 8,
		"turn_duration": 43.5, "boss_attack": 6, "boss_move_interval": 58.3,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 27, "name": "深渊之海·水母群",
		"boss_name": "灯笼鱼", "boss_shape": "OCEAN_ANGLER",
		"subtitle": "深海中回荡着未知生物的呼唤…",
		"color": Color(0.25,0.50,0.80),
		"tile_weights": { "WEAK": 0.32, "ARMOR": 0.09, "ABSORB": 0.05, "NORMAL": 0.54 },
		"bomb_count": 6, "base_clicks": 8,
		"turn_duration": 43.2, "boss_attack": 6, "boss_move_interval": 57.9,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 28, "name": "深渊之海·黑域",
		"boss_name": "幽灵鲸", "boss_shape": "OCEAN_WHALE",
		"subtitle": "深海中回荡着未知生物的呼唤…",
		"color": Color(0.25,0.50,0.80),
		"tile_weights": { "WEAK": 0.32, "ARMOR": 0.09, "ABSORB": 0.05, "NORMAL": 0.54 },
		"bomb_count": 6, "base_clicks": 8,
		"turn_duration": 43.0, "boss_attack": 6, "boss_move_interval": 57.4,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 29, "name": "深渊之海·神殿",
		"boss_name": "珊瑚魔", "boss_shape": "OCEAN_CORAL",
		"subtitle": "深海中回荡着未知生物的呼唤…",
		"color": Color(0.25,0.50,0.80),
		"tile_weights": { "WEAK": 0.31, "ARMOR": 0.09, "ABSORB": 0.05, "NORMAL": 0.54 },
		"bomb_count": 6, "base_clicks": 8,
		"turn_duration": 42.8, "boss_attack": 6, "boss_move_interval": 57.0,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 30, "name": "深渊之海·深渊",
		"boss_name": "利维坦", "boss_shape": "OCEAN_LEVIATHAN",
		"subtitle": "深海中回荡着未知生物的呼唤…",
		"color": Color(0.25,0.50,0.80),
		"tile_weights": { "WEAK": 0.31, "ARMOR": 0.10, "ABSORB": 0.05, "NORMAL": 0.54 },
		"bomb_count": 6, "base_clicks": 8,
		"turn_duration": 42.5, "boss_attack": 6, "boss_move_interval": 56.5,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 31, "name": "熔岩地狱·火口",
		"boss_name": "火蜥蜴", "boss_shape": "LAVA_SALAMANDER",
		"subtitle": "空气灼热得几乎无法呼吸…",
		"color": Color(0.90,0.35,0.15),
		"tile_weights": { "WEAK": 0.31, "ARMOR": 0.10, "ABSORB": 0.05, "NORMAL": 0.54 },
		"bomb_count": 6, "base_clicks": 8,
		"turn_duration": 42.2, "boss_attack": 6, "boss_move_interval": 56.0,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 32, "name": "熔岩地狱·岩桥",
		"boss_name": "熔岩凤凰", "boss_shape": "LAVA_PHOENIX",
		"subtitle": "空气灼热得几乎无法呼吸…",
		"color": Color(0.90,0.35,0.15),
		"tile_weights": { "WEAK": 0.30, "ARMOR": 0.10, "ABSORB": 0.05, "NORMAL": 0.54 },
		"bomb_count": 6, "base_clicks": 8,
		"turn_duration": 42.0, "boss_attack": 6, "boss_move_interval": 55.6,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 33, "name": "熔岩地狱·熔岩河",
		"boss_name": "岩浆巨人", "boss_shape": "LAVA_MAGMA",
		"subtitle": "空气灼热得几乎无法呼吸…",
		"color": Color(0.90,0.35,0.15),
		"tile_weights": { "WEAK": 0.30, "ARMOR": 0.10, "ABSORB": 0.06, "NORMAL": 0.54 },
		"bomb_count": 6, "base_clicks": 8,
		"turn_duration": 41.8, "boss_attack": 6, "boss_move_interval": 55.1,
		"placement_cols": 9, "placement_rows": 6,
		"mine_cols": 9, "mine_rows": 5,
	},
	{
		"id": 34, "name": "熔岩地狱·硫磺洞",
		"boss_name": "火焰虫", "boss_shape": "LAVA_FIREWORM",
		"subtitle": "空气灼热得几乎无法呼吸…",
		"color": Color(0.90,0.35,0.15),
		"tile_weights": { "WEAK": 0.30, "ARMOR": 0.10, "ABSORB": 0.06, "NORMAL": 0.54 },
		"bomb_count": 7, "base_clicks": 8,
		"turn_duration": 41.5, "boss_attack": 7, "boss_move_interval": 54.7,
		"placement_cols": 10, "placement_rows": 6,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 35, "name": "熔岩地狱·黑曜石",
		"boss_name": "烈焰魔", "boss_shape": "LAVA_FIEND",
		"subtitle": "空气灼热得几乎无法呼吸…",
		"color": Color(0.90,0.35,0.15),
		"tile_weights": { "WEAK": 0.30, "ARMOR": 0.11, "ABSORB": 0.06, "NORMAL": 0.54 },
		"bomb_count": 7, "base_clicks": 8,
		"turn_duration": 41.2, "boss_attack": 7, "boss_move_interval": 54.2,
		"placement_cols": 10, "placement_rows": 6,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 36, "name": "熔岩地狱·火焰柱",
		"boss_name": "火龙", "boss_shape": "LAVA_DRAKE",
		"subtitle": "空气灼热得几乎无法呼吸…",
		"color": Color(0.90,0.35,0.15),
		"tile_weights": { "WEAK": 0.29, "ARMOR": 0.11, "ABSORB": 0.06, "NORMAL": 0.54 },
		"bomb_count": 7, "base_clicks": 8,
		"turn_duration": 41.0, "boss_attack": 7, "boss_move_interval": 53.8,
		"placement_cols": 10, "placement_rows": 6,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 37, "name": "熔岩地狱·灰烬路",
		"boss_name": "火元素", "boss_shape": "LAVA_ELEMENTAL",
		"subtitle": "空气灼热得几乎无法呼吸…",
		"color": Color(0.90,0.35,0.15),
		"tile_weights": { "WEAK": 0.29, "ARMOR": 0.11, "ABSORB": 0.06, "NORMAL": 0.54 },
		"bomb_count": 7, "base_clicks": 8,
		"turn_duration": 40.8, "boss_attack": 7, "boss_move_interval": 53.4,
		"placement_cols": 10, "placement_rows": 6,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 38, "name": "熔岩地狱·炼狱",
		"boss_name": "地狱犬", "boss_shape": "LAVA_CERBERUS",
		"subtitle": "空气灼热得几乎无法呼吸…",
		"color": Color(0.90,0.35,0.15),
		"tile_weights": { "WEAK": 0.29, "ARMOR": 0.11, "ABSORB": 0.06, "NORMAL": 0.54 },
		"bomb_count": 7, "base_clicks": 8,
		"turn_duration": 40.5, "boss_attack": 7, "boss_move_interval": 52.9,
		"placement_cols": 10, "placement_rows": 6,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 39, "name": "熔岩地狱·地核",
		"boss_name": "熔岩九头蛇", "boss_shape": "LAVA_PYROHYDRA",
		"subtitle": "空气灼热得几乎无法呼吸…",
		"color": Color(0.90,0.35,0.15),
		"tile_weights": { "WEAK": 0.28, "ARMOR": 0.12, "ABSORB": 0.06, "NORMAL": 0.54 },
		"bomb_count": 7, "base_clicks": 8,
		"turn_duration": 40.2, "boss_attack": 7, "boss_move_interval": 52.5,
		"placement_cols": 10, "placement_rows": 6,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 40, "name": "熔岩地狱·火神殿",
		"boss_name": "伊芙利特", "boss_shape": "LAVA_IFRIT",
		"subtitle": "空气灼热得几乎无法呼吸…",
		"color": Color(0.90,0.35,0.15),
		"tile_weights": { "WEAK": 0.28, "ARMOR": 0.12, "ABSORB": 0.07, "NORMAL": 0.54 },
		"bomb_count": 7, "base_clicks": 9,
		"turn_duration": 40.0, "boss_attack": 7, "boss_move_interval": 52.0,
		"placement_cols": 10, "placement_rows": 6,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 41, "name": "月华殿堂·月门",
		"boss_name": "玉兔", "boss_shape": "MOON_RABBIT",
		"subtitle": "银色月光下一切如梦如幻…",
		"color": Color(0.70,0.65,0.90),
		"tile_weights": { "WEAK": 0.28, "ARMOR": 0.12, "ABSORB": 0.07, "NORMAL": 0.54 },
		"bomb_count": 7, "base_clicks": 9,
		"turn_duration": 39.8, "boss_attack": 7, "boss_move_interval": 51.5,
		"placement_cols": 10, "placement_rows": 6,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 42, "name": "月华殿堂·星阶",
		"boss_name": "月仙", "boss_shape": "MOON_FAIRY",
		"subtitle": "银色月光下一切如梦如幻…",
		"color": Color(0.70,0.65,0.90),
		"tile_weights": { "WEAK": 0.27, "ARMOR": 0.12, "ABSORB": 0.07, "NORMAL": 0.53 },
		"bomb_count": 7, "base_clicks": 9,
		"turn_duration": 39.5, "boss_attack": 8, "boss_move_interval": 51.1,
		"placement_cols": 10, "placement_rows": 6,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 43, "name": "月华殿堂·银池",
		"boss_name": "月下白鹤", "boss_shape": "MOON_CRANE",
		"subtitle": "银色月光下一切如梦如幻…",
		"color": Color(0.70,0.65,0.90),
		"tile_weights": { "WEAK": 0.27, "ARMOR": 0.12, "ABSORB": 0.07, "NORMAL": 0.53 },
		"bomb_count": 7, "base_clicks": 9,
		"turn_duration": 39.2, "boss_attack": 8, "boss_move_interval": 50.6,
		"placement_cols": 10, "placement_rows": 6,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 44, "name": "月华殿堂·云台",
		"boss_name": "银狐", "boss_shape": "MOON_SILVERFOX",
		"subtitle": "银色月光下一切如梦如幻…",
		"color": Color(0.70,0.65,0.90),
		"tile_weights": { "WEAK": 0.27, "ARMOR": 0.13, "ABSORB": 0.07, "NORMAL": 0.53 },
		"bomb_count": 7, "base_clicks": 9,
		"turn_duration": 39.0, "boss_attack": 8, "boss_move_interval": 50.2,
		"placement_cols": 10, "placement_rows": 6,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 45, "name": "月华殿堂·月桂园",
		"boss_name": "皇蛾", "boss_shape": "MOON_MOTH",
		"subtitle": "银色月光下一切如梦如幻…",
		"color": Color(0.70,0.65,0.90),
		"tile_weights": { "WEAK": 0.27, "ARMOR": 0.13, "ABSORB": 0.07, "NORMAL": 0.53 },
		"bomb_count": 7, "base_clicks": 9,
		"turn_duration": 38.8, "boss_attack": 8, "boss_move_interval": 49.8,
		"placement_cols": 10, "placement_rows": 6,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 46, "name": "月华殿堂·仙阁",
		"boss_name": "夜枭", "boss_shape": "MOON_OWL",
		"subtitle": "银色月光下一切如梦如幻…",
		"color": Color(0.70,0.65,0.90),
		"tile_weights": { "WEAK": 0.26, "ARMOR": 0.13, "ABSORB": 0.07, "NORMAL": 0.53 },
		"bomb_count": 7, "base_clicks": 9,
		"turn_duration": 38.5, "boss_attack": 8, "boss_move_interval": 49.3,
		"placement_cols": 10, "placement_rows": 6,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 47, "name": "月华殿堂·水镜",
		"boss_name": "麒麟", "boss_shape": "MOON_QILIN",
		"subtitle": "银色月光下一切如梦如幻…",
		"color": Color(0.70,0.65,0.90),
		"tile_weights": { "WEAK": 0.26, "ARMOR": 0.13, "ABSORB": 0.08, "NORMAL": 0.53 },
		"bomb_count": 7, "base_clicks": 9,
		"turn_duration": 38.2, "boss_attack": 8, "boss_move_interval": 48.9,
		"placement_cols": 10, "placement_rows": 6,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 48, "name": "月华殿堂·光廊",
		"boss_name": "月灵", "boss_shape": "MOON_MOONSPIRIT",
		"subtitle": "银色月光下一切如梦如幻…",
		"color": Color(0.70,0.65,0.90),
		"tile_weights": { "WEAK": 0.26, "ARMOR": 0.14, "ABSORB": 0.08, "NORMAL": 0.53 },
		"bomb_count": 7, "base_clicks": 9,
		"turn_duration": 38.0, "boss_attack": 8, "boss_move_interval": 48.4,
		"placement_cols": 10, "placement_rows": 6,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 49, "name": "月华殿堂·月坛",
		"boss_name": "月卫", "boss_shape": "MOON_GUARDIAN",
		"subtitle": "银色月光下一切如梦如幻…",
		"color": Color(0.70,0.65,0.90),
		"tile_weights": { "WEAK": 0.25, "ARMOR": 0.14, "ABSORB": 0.08, "NORMAL": 0.53 },
		"bomb_count": 7, "base_clicks": 9,
		"turn_duration": 37.8, "boss_attack": 8, "boss_move_interval": 48.0,
		"placement_cols": 10, "placement_rows": 6,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 50, "name": "月华殿堂·月宫",
		"boss_name": "月帝", "boss_shape": "MOON_EMPRESS",
		"subtitle": "银色月光下一切如梦如幻…",
		"color": Color(0.70,0.65,0.90),
		"tile_weights": { "WEAK": 0.25, "ARMOR": 0.14, "ABSORB": 0.08, "NORMAL": 0.53 },
		"bomb_count": 8, "base_clicks": 9,
		"turn_duration": 37.5, "boss_attack": 9, "boss_move_interval": 47.5,
		"placement_cols": 10, "placement_rows": 7,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 51, "name": "永冻冰原·冰原",
		"boss_name": "冰狼", "boss_shape": "ICE_WOLF",
		"subtitle": "寒风刺骨,冰晶在空中闪烁…",
		"color": Color(0.50,0.75,0.95),
		"tile_weights": { "WEAK": 0.25, "ARMOR": 0.14, "ABSORB": 0.08, "NORMAL": 0.53 },
		"bomb_count": 8, "base_clicks": 9,
		"turn_duration": 37.2, "boss_attack": 9, "boss_move_interval": 47.0,
		"placement_cols": 10, "placement_rows": 7,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 52, "name": "永冻冰原·雪谷",
		"boss_name": "霜熊", "boss_shape": "ICE_BEAR",
		"subtitle": "寒风刺骨,冰晶在空中闪烁…",
		"color": Color(0.50,0.75,0.95),
		"tile_weights": { "WEAK": 0.24, "ARMOR": 0.14, "ABSORB": 0.08, "NORMAL": 0.53 },
		"bomb_count": 8, "base_clicks": 9,
		"turn_duration": 37.0, "boss_attack": 9, "boss_move_interval": 46.6,
		"placement_cols": 10, "placement_rows": 7,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 53, "name": "永冻冰原·冰洞",
		"boss_name": "冰巨人", "boss_shape": "ICE_ICEGOLEM",
		"subtitle": "寒风刺骨,冰晶在空中闪烁…",
		"color": Color(0.50,0.75,0.95),
		"tile_weights": { "WEAK": 0.24, "ARMOR": 0.15, "ABSORB": 0.08, "NORMAL": 0.53 },
		"bomb_count": 8, "base_clicks": 9,
		"turn_duration": 36.8, "boss_attack": 9, "boss_move_interval": 46.1,
		"placement_cols": 10, "placement_rows": 7,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 54, "name": "永冻冰原·霜桥",
		"boss_name": "寒魄", "boss_shape": "ICE_WRAITH",
		"subtitle": "寒风刺骨,冰晶在空中闪烁…",
		"color": Color(0.50,0.75,0.95),
		"tile_weights": { "WEAK": 0.24, "ARMOR": 0.15, "ABSORB": 0.09, "NORMAL": 0.53 },
		"bomb_count": 8, "base_clicks": 9,
		"turn_duration": 36.5, "boss_attack": 9, "boss_move_interval": 45.7,
		"placement_cols": 10, "placement_rows": 7,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 55, "name": "永冻冰原·极光",
		"boss_name": "雪人", "boss_shape": "ICE_YETI",
		"subtitle": "寒风刺骨,冰晶在空中闪烁…",
		"color": Color(0.50,0.75,0.95),
		"tile_weights": { "WEAK": 0.24, "ARMOR": 0.15, "ABSORB": 0.09, "NORMAL": 0.53 },
		"bomb_count": 8, "base_clicks": 9,
		"turn_duration": 36.2, "boss_attack": 9, "boss_move_interval": 45.2,
		"placement_cols": 10, "placement_rows": 7,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 56, "name": "永冻冰原·冻湖",
		"boss_name": "冰蛛", "boss_shape": "ICE_ICESPIDER",
		"subtitle": "寒风刺骨,冰晶在空中闪烁…",
		"color": Color(0.50,0.75,0.95),
		"tile_weights": { "WEAK": 0.23, "ARMOR": 0.15, "ABSORB": 0.09, "NORMAL": 0.53 },
		"bomb_count": 8, "base_clicks": 9,
		"turn_duration": 36.0, "boss_attack": 9, "boss_move_interval": 44.8,
		"placement_cols": 10, "placement_rows": 7,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 57, "name": "永冻冰原·冰塔",
		"boss_name": "冰蟒", "boss_shape": "ICE_ICEPYTHON",
		"subtitle": "寒风刺骨,冰晶在空中闪烁…",
		"color": Color(0.50,0.75,0.95),
		"tile_weights": { "WEAK": 0.23, "ARMOR": 0.16, "ABSORB": 0.09, "NORMAL": 0.53 },
		"bomb_count": 8, "base_clicks": 9,
		"turn_duration": 35.8, "boss_attack": 9, "boss_move_interval": 44.4,
		"placement_cols": 10, "placement_rows": 7,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 58, "name": "永冻冰原·暴风",
		"boss_name": "冰凤", "boss_shape": "ICE_FROSTBIRD",
		"subtitle": "寒风刺骨,冰晶在空中闪烁…",
		"color": Color(0.50,0.75,0.95),
		"tile_weights": { "WEAK": 0.23, "ARMOR": 0.16, "ABSORB": 0.09, "NORMAL": 0.53 },
		"bomb_count": 8, "base_clicks": 9,
		"turn_duration": 35.5, "boss_attack": 9, "boss_move_interval": 43.9,
		"placement_cols": 10, "placement_rows": 7,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 59, "name": "永冻冰原·冰窟",
		"boss_name": "猛犸", "boss_shape": "ICE_MAMMOTH",
		"subtitle": "寒风刺骨,冰晶在空中闪烁…",
		"color": Color(0.50,0.75,0.95),
		"tile_weights": { "WEAK": 0.22, "ARMOR": 0.16, "ABSORB": 0.09, "NORMAL": 0.52 },
		"bomb_count": 8, "base_clicks": 9,
		"turn_duration": 35.2, "boss_attack": 10, "boss_move_interval": 43.5,
		"placement_cols": 10, "placement_rows": 7,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 60, "name": "永冻冰原·冰王座",
		"boss_name": "冰后", "boss_shape": "ICE_ICEQUEEN",
		"subtitle": "寒风刺骨,冰晶在空中闪烁…",
		"color": Color(0.50,0.75,0.95),
		"tile_weights": { "WEAK": 0.22, "ARMOR": 0.16, "ABSORB": 0.09, "NORMAL": 0.52 },
		"bomb_count": 8, "base_clicks": 10,
		"turn_duration": 35.0, "boss_attack": 10, "boss_move_interval": 43.0,
		"placement_cols": 10, "placement_rows": 7,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 61, "name": "瘴毒沼泽·沼泽边",
		"boss_name": "毒菇王", "boss_shape": "TOXIC_MUSHROOM",
		"subtitle": "毒雾弥漫,每一步都暗藏危机…",
		"color": Color(0.45,0.75,0.25),
		"tile_weights": { "WEAK": 0.22, "ARMOR": 0.16, "ABSORB": 0.10, "NORMAL": 0.52 },
		"bomb_count": 8, "base_clicks": 10,
		"turn_duration": 34.8, "boss_attack": 10, "boss_move_interval": 42.5,
		"placement_cols": 10, "placement_rows": 7,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 62, "name": "瘴毒沼泽·毒雾",
		"boss_name": "毒蟾", "boss_shape": "TOXIC_TOAD",
		"subtitle": "毒雾弥漫,每一步都暗藏危机…",
		"color": Color(0.45,0.75,0.25),
		"tile_weights": { "WEAK": 0.21, "ARMOR": 0.17, "ABSORB": 0.10, "NORMAL": 0.52 },
		"bomb_count": 8, "base_clicks": 10,
		"turn_duration": 34.5, "boss_attack": 10, "boss_move_interval": 42.1,
		"placement_cols": 10, "placement_rows": 7,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 63, "name": "瘴毒沼泽·枯林",
		"boss_name": "噬人藤", "boss_shape": "TOXIC_VINE",
		"subtitle": "毒雾弥漫,每一步都暗藏危机…",
		"color": Color(0.45,0.75,0.25),
		"tile_weights": { "WEAK": 0.21, "ARMOR": 0.17, "ABSORB": 0.10, "NORMAL": 0.52 },
		"bomb_count": 8, "base_clicks": 10,
		"turn_duration": 34.2, "boss_attack": 10, "boss_move_interval": 41.6,
		"placement_cols": 10, "placement_rows": 7,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 64, "name": "瘴毒沼泽·酸池",
		"boss_name": "酸液蛞蝓", "boss_shape": "TOXIC_SLUG",
		"subtitle": "毒雾弥漫,每一步都暗藏危机…",
		"color": Color(0.45,0.75,0.25),
		"tile_weights": { "WEAK": 0.21, "ARMOR": 0.17, "ABSORB": 0.10, "NORMAL": 0.52 },
		"bomb_count": 8, "base_clicks": 10,
		"turn_duration": 34.0, "boss_attack": 10, "boss_move_interval": 41.2,
		"placement_cols": 10, "placement_rows": 7,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 65, "name": "瘴毒沼泽·孢子园",
		"boss_name": "剧毒蝎", "boss_shape": "TOXIC_SCORPION",
		"subtitle": "毒雾弥漫,每一步都暗藏危机…",
		"color": Color(0.45,0.75,0.25),
		"tile_weights": { "WEAK": 0.21, "ARMOR": 0.17, "ABSORB": 0.10, "NORMAL": 0.52 },
		"bomb_count": 8, "base_clicks": 10,
		"turn_duration": 33.8, "boss_attack": 10, "boss_move_interval": 40.8,
		"placement_cols": 10, "placement_rows": 7,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 66, "name": "瘴毒沼泽·蘑菇洞",
		"boss_name": "腐蚀甲虫", "boss_shape": "TOXIC_BEETLE",
		"subtitle": "毒雾弥漫,每一步都暗藏危机…",
		"color": Color(0.45,0.75,0.25),
		"tile_weights": { "WEAK": 0.20, "ARMOR": 0.18, "ABSORB": 0.10, "NORMAL": 0.52 },
		"bomb_count": 8, "base_clicks": 10,
		"turn_duration": 33.5, "boss_attack": 10, "boss_move_interval": 40.3,
		"placement_cols": 10, "placement_rows": 7,
		"mine_cols": 10, "mine_rows": 6,
	},
	{
		"id": 67, "name": "瘴毒沼泽·瘴气路",
		"boss_name": "幽兰", "boss_shape": "TOXIC_ORCHID",
		"subtitle": "毒雾弥漫,每一步都暗藏危机…",
		"color": Color(0.45,0.75,0.25),
		"tile_weights": { "WEAK": 0.20, "ARMOR": 0.18, "ABSORB": 0.10, "NORMAL": 0.52 },
		"bomb_count": 9, "base_clicks": 10,
		"turn_duration": 33.2, "boss_attack": 11, "boss_move_interval": 39.8,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 68, "name": "瘴毒沼泽·淤泥坑",
		"boss_name": "沼泽怪", "boss_shape": "TOXIC_SWAMPTHING",
		"subtitle": "毒雾弥漫,每一步都暗藏危机…",
		"color": Color(0.45,0.75,0.25),
		"tile_weights": { "WEAK": 0.20, "ARMOR": 0.18, "ABSORB": 0.11, "NORMAL": 0.52 },
		"bomb_count": 9, "base_clicks": 10,
		"turn_duration": 33.0, "boss_attack": 11, "boss_move_interval": 39.4,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 69, "name": "瘴毒沼泽·毒泉",
		"boss_name": "毒九头蛇", "boss_shape": "TOXIC_TOXHYDRA",
		"subtitle": "毒雾弥漫,每一步都暗藏危机…",
		"color": Color(0.45,0.75,0.25),
		"tile_weights": { "WEAK": 0.19, "ARMOR": 0.18, "ABSORB": 0.11, "NORMAL": 0.52 },
		"bomb_count": 9, "base_clicks": 10,
		"turn_duration": 32.8, "boss_attack": 11, "boss_move_interval": 39.0,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 70, "name": "瘴毒沼泽·瘟疫殿",
		"boss_name": "瘟疫使", "boss_shape": "TOXIC_PLAGUELORD",
		"subtitle": "毒雾弥漫,每一步都暗藏危机…",
		"color": Color(0.45,0.75,0.25),
		"tile_weights": { "WEAK": 0.19, "ARMOR": 0.18, "ABSORB": 0.11, "NORMAL": 0.52 },
		"bomb_count": 9, "base_clicks": 10,
		"turn_duration": 32.5, "boss_attack": 11, "boss_move_interval": 38.5,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 71, "name": "幽灵古城·城门",
		"boss_name": "幽灵武士", "boss_shape": "GHOST_SAMURAI",
		"subtitle": "鬼火飘摇,亡灵在暗处窥视…",
		"color": Color(0.60,0.50,0.70),
		"tile_weights": { "WEAK": 0.19, "ARMOR": 0.19, "ABSORB": 0.11, "NORMAL": 0.52 },
		"bomb_count": 9, "base_clicks": 10,
		"turn_duration": 32.2, "boss_attack": 11, "boss_move_interval": 38.0,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 72, "name": "幽灵古城·幽巷",
		"boss_name": "怨灵艺伎", "boss_shape": "GHOST_GEISHA",
		"subtitle": "鬼火飘摇,亡灵在暗处窥视…",
		"color": Color(0.60,0.50,0.70),
		"tile_weights": { "WEAK": 0.18, "ARMOR": 0.19, "ABSORB": 0.11, "NORMAL": 0.52 },
		"bomb_count": 9, "base_clicks": 10,
		"turn_duration": 32.0, "boss_attack": 11, "boss_move_interval": 37.6,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 73, "name": "幽灵古城·灯笼街",
		"boss_name": "灯笼鬼", "boss_shape": "GHOST_LANTERN",
		"subtitle": "鬼火飘摇,亡灵在暗处窥视…",
		"color": Color(0.60,0.50,0.70),
		"tile_weights": { "WEAK": 0.18, "ARMOR": 0.19, "ABSORB": 0.11, "NORMAL": 0.52 },
		"bomb_count": 9, "base_clicks": 10,
		"turn_duration": 31.8, "boss_attack": 11, "boss_move_interval": 37.1,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 74, "name": "幽灵古城·枯井",
		"boss_name": "骸骨兵", "boss_shape": "GHOST_SKELETON",
		"subtitle": "鬼火飘摇,亡灵在暗处窥视…",
		"color": Color(0.60,0.50,0.70),
		"tile_weights": { "WEAK": 0.18, "ARMOR": 0.19, "ABSORB": 0.11, "NORMAL": 0.52 },
		"bomb_count": 9, "base_clicks": 10,
		"turn_duration": 31.5, "boss_attack": 11, "boss_move_interval": 36.7,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 75, "name": "幽灵古城·茶馆",
		"boss_name": "哭泣女", "boss_shape": "GHOST_BANSHEE",
		"subtitle": "鬼火飘摇,亡灵在暗处窥视…",
		"color": Color(0.60,0.50,0.70),
		"tile_weights": { "WEAK": 0.18, "ARMOR": 0.20, "ABSORB": 0.12, "NORMAL": 0.51 },
		"bomb_count": 9, "base_clicks": 10,
		"turn_duration": 31.2, "boss_attack": 12, "boss_move_interval": 36.2,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 76, "name": "幽灵古城·戏楼",
		"boss_name": "死神", "boss_shape": "GHOST_REAPER",
		"subtitle": "鬼火飘摇,亡灵在暗处窥视…",
		"color": Color(0.60,0.50,0.70),
		"tile_weights": { "WEAK": 0.17, "ARMOR": 0.20, "ABSORB": 0.12, "NORMAL": 0.51 },
		"bomb_count": 9, "base_clicks": 10,
		"turn_duration": 31.0, "boss_attack": 12, "boss_move_interval": 35.8,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 77, "name": "幽灵古城·坟场",
		"boss_name": "人偶师", "boss_shape": "GHOST_PUPPET",
		"subtitle": "鬼火飘摇,亡灵在暗处窥视…",
		"color": Color(0.60,0.50,0.70),
		"tile_weights": { "WEAK": 0.17, "ARMOR": 0.20, "ABSORB": 0.12, "NORMAL": 0.51 },
		"bomb_count": 9, "base_clicks": 10,
		"turn_duration": 30.8, "boss_attack": 12, "boss_move_interval": 35.4,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 78, "name": "幽灵古城·钟声",
		"boss_name": "影鬼", "boss_shape": "GHOST_SHADOWGHOST",
		"subtitle": "鬼火飘摇,亡灵在暗处窥视…",
		"color": Color(0.60,0.50,0.70),
		"tile_weights": { "WEAK": 0.17, "ARMOR": 0.20, "ABSORB": 0.12, "NORMAL": 0.51 },
		"bomb_count": 9, "base_clicks": 10,
		"turn_duration": 30.5, "boss_attack": 12, "boss_move_interval": 34.9,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 79, "name": "幽灵古城·鬼王路",
		"boss_name": "怨灵王", "boss_shape": "GHOST_WRAITHKING",
		"subtitle": "鬼火飘摇,亡灵在暗处窥视…",
		"color": Color(0.60,0.50,0.70),
		"tile_weights": { "WEAK": 0.16, "ARMOR": 0.20, "ABSORB": 0.12, "NORMAL": 0.51 },
		"bomb_count": 9, "base_clicks": 10,
		"turn_duration": 30.2, "boss_attack": 12, "boss_move_interval": 34.4,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 80, "name": "幽灵古城·地府",
		"boss_name": "巫妖", "boss_shape": "GHOST_LICH",
		"subtitle": "鬼火飘摇,亡灵在暗处窥视…",
		"color": Color(0.60,0.50,0.70),
		"tile_weights": { "WEAK": 0.16, "ARMOR": 0.21, "ABSORB": 0.12, "NORMAL": 0.51 },
		"bomb_count": 9, "base_clicks": 11,
		"turn_duration": 30.0, "boss_attack": 12, "boss_move_interval": 34.0,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 81, "name": "混沌裂隙·裂口",
		"boss_name": "混沌拟态", "boss_shape": "CHAOS_MIMIC",
		"subtitle": "现实在此扭曲崩塌…",
		"color": Color(0.80,0.30,0.60),
		"tile_weights": { "WEAK": 0.16, "ARMOR": 0.21, "ABSORB": 0.12, "NORMAL": 0.51 },
		"bomb_count": 9, "base_clicks": 11,
		"turn_duration": 29.8, "boss_attack": 12, "boss_move_interval": 33.5,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 82, "name": "混沌裂隙·碎空",
		"boss_name": "千眼", "boss_shape": "CHAOS_EYE",
		"subtitle": "现实在此扭曲崩塌…",
		"color": Color(0.80,0.30,0.60),
		"tile_weights": { "WEAK": 0.15, "ARMOR": 0.21, "ABSORB": 0.12, "NORMAL": 0.51 },
		"bomb_count": 9, "base_clicks": 11,
		"turn_duration": 29.5, "boss_attack": 12, "boss_move_interval": 33.1,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 83, "name": "混沌裂隙·扭曲路",
		"boss_name": "混沌粘液", "boss_shape": "CHAOS_BLOB",
		"subtitle": "现实在此扭曲崩塌…",
		"color": Color(0.80,0.30,0.60),
		"tile_weights": { "WEAK": 0.15, "ARMOR": 0.21, "ABSORB": 0.13, "NORMAL": 0.51 },
		"bomb_count": 9, "base_clicks": 11,
		"turn_duration": 29.2, "boss_attack": 12, "boss_move_interval": 32.6,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 84, "name": "混沌裂隙·镜之廊",
		"boss_name": "奇美拉", "boss_shape": "CHAOS_CHIMERA",
		"subtitle": "现实在此扭曲崩塌…",
		"color": Color(0.80,0.30,0.60),
		"tile_weights": { "WEAK": 0.15, "ARMOR": 0.21, "ABSORB": 0.13, "NORMAL": 0.51 },
		"bomb_count": 10, "base_clicks": 11,
		"turn_duration": 29.0, "boss_attack": 13, "boss_move_interval": 32.2,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 85, "name": "混沌裂隙·逆时钟",
		"boss_name": "裂隙虫", "boss_shape": "CHAOS_RIFTWORM",
		"subtitle": "现实在此扭曲崩塌…",
		"color": Color(0.80,0.30,0.60),
		"tile_weights": { "WEAK": 0.15, "ARMOR": 0.22, "ABSORB": 0.13, "NORMAL": 0.51 },
		"bomb_count": 10, "base_clicks": 11,
		"turn_duration": 28.8, "boss_attack": 13, "boss_move_interval": 31.8,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 86, "name": "混沌裂隙·虚像",
		"boss_name": "混沌石像", "boss_shape": "CHAOS_CHAOSGARGOYLE",
		"subtitle": "现实在此扭曲崩塌…",
		"color": Color(0.80,0.30,0.60),
		"tile_weights": { "WEAK": 0.14, "ARMOR": 0.22, "ABSORB": 0.13, "NORMAL": 0.51 },
		"bomb_count": 10, "base_clicks": 11,
		"turn_duration": 28.5, "boss_attack": 13, "boss_move_interval": 31.3,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 87, "name": "混沌裂隙·混沌海",
		"boss_name": "混沌巨人", "boss_shape": "CHAOS_CHAOSGOLEM",
		"subtitle": "现实在此扭曲崩塌…",
		"color": Color(0.80,0.30,0.60),
		"tile_weights": { "WEAK": 0.14, "ARMOR": 0.22, "ABSORB": 0.13, "NORMAL": 0.51 },
		"bomb_count": 10, "base_clicks": 11,
		"turn_duration": 28.2, "boss_attack": 13, "boss_move_interval": 30.9,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 88, "name": "混沌裂隙·断层",
		"boss_name": "混沌巫师", "boss_shape": "CHAOS_CHAOSWITCH",
		"subtitle": "现实在此扭曲崩塌…",
		"color": Color(0.80,0.30,0.60),
		"tile_weights": { "WEAK": 0.14, "ARMOR": 0.22, "ABSORB": 0.13, "NORMAL": 0.51 },
		"bomb_count": 10, "base_clicks": 11,
		"turn_duration": 28.0, "boss_attack": 13, "boss_move_interval": 30.4,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 89, "name": "混沌裂隙·终焉",
		"boss_name": "混沌龙", "boss_shape": "CHAOS_CHAOSDRAGON",
		"subtitle": "现实在此扭曲崩塌…",
		"color": Color(0.80,0.30,0.60),
		"tile_weights": { "WEAK": 0.13, "ARMOR": 0.23, "ABSORB": 0.13, "NORMAL": 0.51 },
		"bomb_count": 10, "base_clicks": 11,
		"turn_duration": 27.8, "boss_attack": 13, "boss_move_interval": 30.0,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 90, "name": "混沌裂隙·混沌核心",
		"boss_name": "混沌主宰", "boss_shape": "CHAOS_CHAOSLORD",
		"subtitle": "现实在此扭曲崩塌…",
		"color": Color(0.80,0.30,0.60),
		"tile_weights": { "WEAK": 0.13, "ARMOR": 0.23, "ABSORB": 0.14, "NORMAL": 0.51 },
		"bomb_count": 10, "base_clicks": 11,
		"turn_duration": 27.5, "boss_attack": 13, "boss_move_interval": 29.5,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 91, "name": "虚空深渊·虚空门",
		"boss_name": "虚空幻影", "boss_shape": "VOID_PHANTOM",
		"subtitle": "虚空中只有无尽的沉默…",
		"color": Color(0.40,0.25,0.65),
		"tile_weights": { "WEAK": 0.13, "ARMOR": 0.23, "ABSORB": 0.14, "NORMAL": 0.51 },
		"bomb_count": 10, "base_clicks": 11,
		"turn_duration": 27.2, "boss_attack": 13, "boss_move_interval": 29.0,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 92, "name": "虚空深渊·暗星",
		"boss_name": "虚空水晶", "boss_shape": "VOID_CRYSTAL",
		"subtitle": "虚空中只有无尽的沉默…",
		"color": Color(0.40,0.25,0.65),
		"tile_weights": { "WEAK": 0.12, "ARMOR": 0.23, "ABSORB": 0.14, "NORMAL": 0.50 },
		"bomb_count": 10, "base_clicks": 11,
		"turn_duration": 27.0, "boss_attack": 14, "boss_move_interval": 28.6,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 93, "name": "虚空深渊·星尘",
		"boss_name": "虚空巨蟒", "boss_shape": "VOID_VOIDSERPENT",
		"subtitle": "虚空中只有无尽的沉默…",
		"color": Color(0.40,0.25,0.65),
		"tile_weights": { "WEAK": 0.12, "ARMOR": 0.23, "ABSORB": 0.14, "NORMAL": 0.50 },
		"bomb_count": 10, "base_clicks": 11,
		"turn_duration": 26.8, "boss_attack": 14, "boss_move_interval": 28.1,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 94, "name": "虚空深渊·黑洞边",
		"boss_name": "虚空泰坦", "boss_shape": "VOID_VOIDTITAN",
		"subtitle": "虚空中只有无尽的沉默…",
		"color": Color(0.40,0.25,0.65),
		"tile_weights": { "WEAK": 0.12, "ARMOR": 0.24, "ABSORB": 0.14, "NORMAL": 0.50 },
		"bomb_count": 10, "base_clicks": 11,
		"turn_duration": 26.5, "boss_attack": 14, "boss_move_interval": 27.7,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 95, "name": "虚空深渊·时空裂",
		"boss_name": "虚空收割者", "boss_shape": "VOID_VOIDREAPER",
		"subtitle": "虚空中只有无尽的沉默…",
		"color": Color(0.40,0.25,0.65),
		"tile_weights": { "WEAK": 0.12, "ARMOR": 0.24, "ABSORB": 0.14, "NORMAL": 0.50 },
		"bomb_count": 10, "base_clicks": 11,
		"turn_duration": 26.2, "boss_attack": 14, "boss_move_interval": 27.2,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 96, "name": "虚空深渊·银河",
		"boss_name": "虚空九头蛇", "boss_shape": "VOID_VOIDHYDRA",
		"subtitle": "虚空中只有无尽的沉默…",
		"color": Color(0.40,0.25,0.65),
		"tile_weights": { "WEAK": 0.11, "ARMOR": 0.24, "ABSORB": 0.14, "NORMAL": 0.50 },
		"bomb_count": 10, "base_clicks": 11,
		"turn_duration": 26.0, "boss_attack": 14, "boss_move_interval": 26.8,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 97, "name": "虚空深渊·湮灭",
		"boss_name": "虚空凤凰", "boss_shape": "VOID_VOIDPHOENIX",
		"subtitle": "虚空中只有无尽的沉默…",
		"color": Color(0.40,0.25,0.65),
		"tile_weights": { "WEAK": 0.11, "ARMOR": 0.24, "ABSORB": 0.15, "NORMAL": 0.50 },
		"bomb_count": 10, "base_clicks": 11,
		"turn_duration": 25.8, "boss_attack": 14, "boss_move_interval": 26.4,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 98, "name": "虚空深渊·奇点",
		"boss_name": "虚空魔王", "boss_shape": "VOID_VOIDDEMON",
		"subtitle": "虚空中只有无尽的沉默…",
		"color": Color(0.40,0.25,0.65),
		"tile_weights": { "WEAK": 0.11, "ARMOR": 0.25, "ABSORB": 0.15, "NORMAL": 0.50 },
		"bomb_count": 10, "base_clicks": 11,
		"turn_duration": 25.5, "boss_attack": 14, "boss_move_interval": 25.9,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 99, "name": "虚空深渊·终极",
		"boss_name": "虚空巨龙", "boss_shape": "VOID_VOIDDRAGON",
		"subtitle": "虚空中只有无尽的沉默…",
		"color": Color(0.40,0.25,0.65),
		"tile_weights": { "WEAK": 0.10, "ARMOR": 0.25, "ABSORB": 0.15, "NORMAL": 0.50 },
		"bomb_count": 10, "base_clicks": 11,
		"turn_duration": 25.2, "boss_attack": 14, "boss_move_interval": 25.5,
		"placement_cols": 11, "placement_rows": 7,
		"mine_cols": 11, "mine_rows": 7,
	},
	{
		"id": 100, "name": "虚空深渊·虚空神座",
		"boss_name": "虚空神", "boss_shape": "VOID_VOIDGOD",
		"subtitle": "虚空中只有无尽的沉默…",
		"color": Color(0.40,0.25,0.65),
		"tile_weights": { "WEAK": 0.10, "ARMOR": 0.25, "ABSORB": 0.15, "NORMAL": 0.50 },
		"bomb_count": 11, "base_clicks": 12,
		"turn_duration": 25.0, "boss_attack": 15, "boss_move_interval": 25.0,
		"placement_cols": 12, "placement_rows": 8,
		"mine_cols": 12, "mine_rows": 8,
	},
]

const BOSS_TEXTURE_MAP = {
	"BAMBOO_TANUKI": "res://assets/sprites/boss/boss_bamboo_tanuki.png",
	"BAMBOO_KITSUNE": "res://assets/sprites/boss/boss_bamboo_kitsune.png",
	"BAMBOO_TENGU": "res://assets/sprites/boss/boss_bamboo_tengu.png",
	"BAMBOO_ONI": "res://assets/sprites/boss/boss_bamboo_oni.png",
	"BAMBOO_JOROUGUMO": "res://assets/sprites/boss/boss_bamboo_jorougumo.png",
	"BAMBOO_HEBI": "res://assets/sprites/boss/boss_bamboo_hebi.png",
	"BAMBOO_TSURU": "res://assets/sprites/boss/boss_bamboo_tsuru.png",
	"BAMBOO_KUMA": "res://assets/sprites/boss/boss_bamboo_kuma.png",
	"BAMBOO_ENMA": "res://assets/sprites/boss/boss_bamboo_enma.png",
	"BAMBOO_RYUU": "res://assets/sprites/boss/boss_bamboo_ryuu.png",
	"GEAR_AUTOMATON": "res://assets/sprites/boss/boss_gear_automaton.png",
	"GEAR_TANK": "res://assets/sprites/boss/boss_gear_tank.png",
	"GEAR_ARACHNE": "res://assets/sprites/boss/boss_gear_arachne.png",
	"GEAR_DRILL": "res://assets/sprites/boss/boss_gear_drill.png",
	"GEAR_CANNON": "res://assets/sprites/boss/boss_gear_cannon.png",
	"GEAR_HAWK": "res://assets/sprites/boss/boss_gear_hawk.png",
	"GEAR_BRONZE": "res://assets/sprites/boss/boss_gear_bronze.png",
	"GEAR_WORM": "res://assets/sprites/boss/boss_gear_worm.png",
	"GEAR_KNIGHT": "res://assets/sprites/boss/boss_gear_knight.png",
	"GEAR_COLOSSUS": "res://assets/sprites/boss/boss_gear_colossus.png",
	"OCEAN_JELLY": "res://assets/sprites/boss/boss_ocean_jelly.png",
	"OCEAN_SHARK": "res://assets/sprites/boss/boss_ocean_shark.png",
	"OCEAN_KRAKEN": "res://assets/sprites/boss/boss_ocean_kraken.png",
	"OCEAN_SIREN": "res://assets/sprites/boss/boss_ocean_siren.png",
	"OCEAN_CRAB": "res://assets/sprites/boss/boss_ocean_crab.png",
	"OCEAN_SEASERPENT": "res://assets/sprites/boss/boss_ocean_seaserpent.png",
	"OCEAN_ANGLER": "res://assets/sprites/boss/boss_ocean_angler.png",
	"OCEAN_WHALE": "res://assets/sprites/boss/boss_ocean_whale.png",
	"OCEAN_CORAL": "res://assets/sprites/boss/boss_ocean_coral.png",
	"OCEAN_LEVIATHAN": "res://assets/sprites/boss/boss_ocean_leviathan.png",
	"LAVA_SALAMANDER": "res://assets/sprites/boss/boss_lava_salamander.png",
	"LAVA_PHOENIX": "res://assets/sprites/boss/boss_lava_phoenix.png",
	"LAVA_MAGMA": "res://assets/sprites/boss/boss_lava_magma.png",
	"LAVA_FIREWORM": "res://assets/sprites/boss/boss_lava_fireworm.png",
	"LAVA_FIEND": "res://assets/sprites/boss/boss_lava_fiend.png",
	"LAVA_DRAKE": "res://assets/sprites/boss/boss_lava_drake.png",
	"LAVA_ELEMENTAL": "res://assets/sprites/boss/boss_lava_elemental.png",
	"LAVA_CERBERUS": "res://assets/sprites/boss/boss_lava_cerberus.png",
	"LAVA_PYROHYDRA": "res://assets/sprites/boss/boss_lava_pyrohydra.png",
	"LAVA_IFRIT": "res://assets/sprites/boss/boss_lava_ifrit.png",
	"MOON_RABBIT": "res://assets/sprites/boss/boss_moon_rabbit.png",
	"MOON_FAIRY": "res://assets/sprites/boss/boss_moon_fairy.png",
	"MOON_CRANE": "res://assets/sprites/boss/boss_moon_crane.png",
	"MOON_SILVERFOX": "res://assets/sprites/boss/boss_moon_silverfox.png",
	"MOON_MOTH": "res://assets/sprites/boss/boss_moon_moth.png",
	"MOON_OWL": "res://assets/sprites/boss/boss_moon_owl.png",
	"MOON_QILIN": "res://assets/sprites/boss/boss_moon_qilin.png",
	"MOON_MOONSPIRIT": "res://assets/sprites/boss/boss_moon_moonspirit.png",
	"MOON_GUARDIAN": "res://assets/sprites/boss/boss_moon_guardian.png",
	"MOON_EMPRESS": "res://assets/sprites/boss/boss_moon_empress.png",
	"ICE_WOLF": "res://assets/sprites/boss/boss_ice_wolf.png",
	"ICE_BEAR": "res://assets/sprites/boss/boss_ice_bear.png",
	"ICE_ICEGOLEM": "res://assets/sprites/boss/boss_ice_icegolem.png",
	"ICE_WRAITH": "res://assets/sprites/boss/boss_ice_wraith.png",
	"ICE_YETI": "res://assets/sprites/boss/boss_ice_yeti.png",
	"ICE_ICESPIDER": "res://assets/sprites/boss/boss_ice_icespider.png",
	"ICE_ICEPYTHON": "res://assets/sprites/boss/boss_ice_icepython.png",
	"ICE_FROSTBIRD": "res://assets/sprites/boss/boss_ice_frostbird.png",
	"ICE_MAMMOTH": "res://assets/sprites/boss/boss_ice_mammoth.png",
	"ICE_ICEQUEEN": "res://assets/sprites/boss/boss_ice_icequeen.png",
	"TOXIC_MUSHROOM": "res://assets/sprites/boss/boss_toxic_mushroom.png",
	"TOXIC_TOAD": "res://assets/sprites/boss/boss_toxic_toad.png",
	"TOXIC_VINE": "res://assets/sprites/boss/boss_toxic_vine.png",
	"TOXIC_SLUG": "res://assets/sprites/boss/boss_toxic_slug.png",
	"TOXIC_SCORPION": "res://assets/sprites/boss/boss_toxic_scorpion.png",
	"TOXIC_BEETLE": "res://assets/sprites/boss/boss_toxic_beetle.png",
	"TOXIC_ORCHID": "res://assets/sprites/boss/boss_toxic_orchid.png",
	"TOXIC_SWAMPTHING": "res://assets/sprites/boss/boss_toxic_swampthing.png",
	"TOXIC_TOXHYDRA": "res://assets/sprites/boss/boss_toxic_toxhydra.png",
	"TOXIC_PLAGUELORD": "res://assets/sprites/boss/boss_toxic_plaguelord.png",
	"GHOST_SAMURAI": "res://assets/sprites/boss/boss_ghost_samurai.png",
	"GHOST_GEISHA": "res://assets/sprites/boss/boss_ghost_geisha.png",
	"GHOST_LANTERN": "res://assets/sprites/boss/boss_ghost_lantern.png",
	"GHOST_SKELETON": "res://assets/sprites/boss/boss_ghost_skeleton.png",
	"GHOST_BANSHEE": "res://assets/sprites/boss/boss_ghost_banshee.png",
	"GHOST_REAPER": "res://assets/sprites/boss/boss_ghost_reaper.png",
	"GHOST_PUPPET": "res://assets/sprites/boss/boss_ghost_puppet.png",
	"GHOST_SHADOWGHOST": "res://assets/sprites/boss/boss_ghost_shadowghost.png",
	"GHOST_WRAITHKING": "res://assets/sprites/boss/boss_ghost_wraithking.png",
	"GHOST_LICH": "res://assets/sprites/boss/boss_ghost_lich.png",
	"CHAOS_MIMIC": "res://assets/sprites/boss/boss_chaos_mimic.png",
	"CHAOS_EYE": "res://assets/sprites/boss/boss_chaos_eye.png",
	"CHAOS_BLOB": "res://assets/sprites/boss/boss_chaos_blob.png",
	"CHAOS_CHIMERA": "res://assets/sprites/boss/boss_chaos_chimera.png",
	"CHAOS_RIFTWORM": "res://assets/sprites/boss/boss_chaos_riftworm.png",
	"CHAOS_CHAOSGARGOYLE": "res://assets/sprites/boss/boss_chaos_chaosgargoyle.png",
	"CHAOS_CHAOSGOLEM": "res://assets/sprites/boss/boss_chaos_chaosgolem.png",
	"CHAOS_CHAOSWITCH": "res://assets/sprites/boss/boss_chaos_chaoswitch.png",
	"CHAOS_CHAOSDRAGON": "res://assets/sprites/boss/boss_chaos_chaosdragon.png",
	"CHAOS_CHAOSLORD": "res://assets/sprites/boss/boss_chaos_chaoslord.png",
	"VOID_PHANTOM": "res://assets/sprites/boss/boss_void_phantom.png",
	"VOID_CRYSTAL": "res://assets/sprites/boss/boss_void_crystal.png",
	"VOID_VOIDSERPENT": "res://assets/sprites/boss/boss_void_voidserpent.png",
	"VOID_VOIDTITAN": "res://assets/sprites/boss/boss_void_voidtitan.png",
	"VOID_VOIDREAPER": "res://assets/sprites/boss/boss_void_voidreaper.png",
	"VOID_VOIDHYDRA": "res://assets/sprites/boss/boss_void_voidhydra.png",
	"VOID_VOIDPHOENIX": "res://assets/sprites/boss/boss_void_voidphoenix.png",
	"VOID_VOIDDEMON": "res://assets/sprites/boss/boss_void_voiddemon.png",
	"VOID_VOIDDRAGON": "res://assets/sprites/boss/boss_void_voiddragon.png",
	"VOID_VOIDGOD": "res://assets/sprites/boss/boss_void_voidgod.png",
}

# ============================================================
#  查询接口  —  100关唯一对应
# ============================================================

func get_level(floor_number: int) -> Dictionary:
	var idx = (floor_number - 1) % LEVELS.size()
	return LEVELS[idx]

func get_cycle(floor_number: int) -> int:
	return (floor_number - 1) / LEVELS.size()

func get_level_name(floor_number: int) -> String:
	return get_level(floor_number)["name"]

func get_boss_name(floor_number: int) -> String:
	return get_level(floor_number)["boss_name"]

func get_level_subtitle(floor_number: int) -> String:
	return get_level(floor_number)["subtitle"]

func get_level_color(floor_number: int) -> Color:
	return get_level(floor_number)["color"]

# -- 棋盘大小 --

func get_placement_cols(floor_number: int) -> int:
	var level = get_level(floor_number)
	var cycle = get_cycle(floor_number)
	return level["placement_cols"] + cycle

func get_placement_rows(floor_number: int) -> int:
	return get_level(floor_number)["placement_rows"]

func get_mine_cols(floor_number: int) -> int:
	var level = get_level(floor_number)
	var cycle = get_cycle(floor_number)
	var base = level["mine_cols"] + cycle
	var extra = roundi((GameSettings.mine_difficulty - 1.0) * 3.0)
	return maxi(base + extra, 6)

func get_mine_rows(floor_number: int) -> int:
	var base = get_level(floor_number)["mine_rows"]
	var extra = roundi((GameSettings.mine_difficulty - 1.0) * 1.5)
	return maxi(base + extra, 3)

func get_boss_shape(floor_number: int) -> Array:
	var key = get_level(floor_number)["boss_shape"]
	var sz = BOSS_GRID_SIZE[key]
	var arr = []
	for y in range(sz.y):
		for x in range(sz.x):
			arr.append(Vector2i(x, y))
	return arr

func get_boss_grid_size(floor_number: int) -> Vector2i:
	var key = get_level(floor_number)["boss_shape"]
	return BOSS_GRID_SIZE[key]

func get_boss_texture_path(floor_number: int) -> String:
	var key = get_level(floor_number)["boss_shape"]
	return BOSS_TEXTURE_MAP[key]

const BACKGROUND_PATHS: Array = [
	"res://assets/sprites/bg/bg_bamboo_grove.png",
	"res://assets/sprites/bg/bg_gear_fortress.png",
	"res://assets/sprites/bg/bg_deep_ocean.png",
	"res://assets/sprites/bg/bg_lava_hellscape.png",
	"res://assets/sprites/bg/bg_moon_palace.png",
	"res://assets/sprites/bg/bg_frozen_tundra.png",
	"res://assets/sprites/bg/bg_toxic_swamp.png",
	"res://assets/sprites/bg/bg_ghost_city.png",
	"res://assets/sprites/bg/bg_chaos_rift.png",
	"res://assets/sprites/bg/bg_void_abyss.png",
]

func get_background_texture_path(floor_number: int) -> String:
	var idx = ((floor_number - 1) / 10) % BACKGROUND_PATHS.size()
	return BACKGROUND_PATHS[idx]

func get_cell_size(floor_number: int) -> int:
	var p_cols = get_placement_cols(floor_number)
	var p_rows = get_placement_rows(floor_number)
	var m_cols = get_mine_cols(floor_number)
	var m_rows = get_mine_rows(floor_number)
	var max_cols = max(p_cols, m_cols)
	var size_by_w = int(1760.0 / max_cols)
	var size_by_h = int(880.0 / (p_rows + m_rows))
	return min(size_by_w, size_by_h)

# -- 难度参数（含周期递增）--

func get_bomb_count(floor_number: int) -> int:
	var level = get_level(floor_number)
	var cycle = get_cycle(floor_number)
	var base = level["bomb_count"] + cycle * 2
	var d = GameSettings.mine_difficulty
	if is_equal_approx(d, 1.0):
		return base
	var cols = get_mine_cols(floor_number)
	var rows = get_mine_rows(floor_number)
	var base_cols = level["mine_cols"] + cycle
	var base_rows = level["mine_rows"]
	var base_density = float(base) / float(base_cols * base_rows)
	var density_mult = 0.7 + 0.3 * d
	return maxi(roundi(cols * rows * base_density * density_mult), 2)

func get_turn_duration(floor_number: int) -> float:
	var level = get_level(floor_number)
	var cycle = get_cycle(floor_number)
	return maxf(level["turn_duration"] - cycle * 3.0, 15.0)

func get_boss_attack(floor_number: int) -> int:
	var level = get_level(floor_number)
	var cycle = get_cycle(floor_number)
	return level["boss_attack"] + cycle * 3

func get_boss_move_interval(floor_number: int) -> float:
	var level = get_level(floor_number)
	var cycle = get_cycle(floor_number)
	return maxf(level["boss_move_interval"] - cycle * 5.0, 18.0)

func get_tile_weights(floor_number: int) -> Dictionary:
	return get_level(floor_number)["tile_weights"]

func get_hp_multiplier(floor_number: int) -> float:
	var cycle = get_cycle(floor_number)
	var base = 1.0 + cycle * 0.5
	return base * GameSettings.boss_hp_mult

func get_max_clicks(floor_number: int) -> int:
	var level = get_level(floor_number)
	var cycle = get_cycle(floor_number)
	return level["base_clicks"] + cycle * 3

# -- 故事卡片 --

const STORY_DATA = {
	1:  { "title": "十境传说",     "text": "传说，世界由十座浮空之境相连。竹林、齿轮、深海、熔岩、月华……万物在此共生。", "art": "res://assets/sprites/story/story_01_world.png" },
	11: { "title": "裂隙降临",     "text": "直到——裂缝出现。虚空的力量渗入每一座境界，怪物从裂隙中涌出。", "art": "res://assets/sprites/story/story_02_invasion.png" },
	21: { "title": "炸弹人觉醒",   "text": "废墟之中，一个身影站了起来。炸弹人——唯一能引爆封印之力的人。", "art": "res://assets/sprites/story/story_03_hero.png" },
	41: { "title": "穿越十境",     "text": "从竹林秘境出发，穿越十座境界。探索、收集、引爆——这就是前进的唯一方式。", "art": "res://assets/sprites/story/story_04_journey.png" },
	71: { "title": "封印松动",     "text": "每击败一个守卫，封印便松动一分。力量在积累，希望在生长。", "art": "res://assets/sprites/story/story_05_victory.png" },
	91: { "title": "终焉之门",     "text": "当十境之门全部打开——虚空深渊的虚空神将在终焉等待。踏出这一步的人——不需要理由。", "art": "res://assets/sprites/story/story_06_final.png" },
}

func should_show_story_card(floor_number: int) -> bool:
	return STORY_DATA.has(floor_number)

func get_story_art_path(floor_number: int) -> String:
	if STORY_DATA.has(floor_number):
		return STORY_DATA[floor_number]["art"]
	return ""

func get_story_title(floor_number: int) -> String:
	if STORY_DATA.has(floor_number):
		return STORY_DATA[floor_number]["title"]
	return ""

func get_story_text(floor_number: int) -> String:
	if STORY_DATA.has(floor_number):
		return STORY_DATA[floor_number]["text"]
	return ""

